### ISSUE TITLE
NGM Forward Art - missing dng, only bayer available

### ISSUE THREAD

**Issue by MasterPIC** [KillerInk/FreeDcam#1]
[log.txt](https://github.com/KillerInk/FreeDcam/files/1440675/log.txt)

Phone Model:
NGM Forward Art_MTK

FreeDcam Version:
Last release

Problem Description:
Only bayer (and jpeg) is available, dng is possible only by manually converting from bayer. 
On an older release the app offered also dng as output format by saving both jpeg and dng after taking a shot.

**Comment by KillerInk** [comment]
I dont have a Device wich support Camera1 and Raw.
From your Log the DngProfile gets written. 
The Problem should be in the [PictureFormatHandler](https://github.com/KillerInk/FreeDcam/blob/master/app/src/main/java/freed/cam/apis/camera1/parameters/modes/PictureFormatHandler.java#L48-L72)

**Comment by KillerInk** [comment]
alpha26 should work again

**Comment by MasterPIC** [comment]
Yes, it works again.

Thanks
Armando
