### ISSUE TITLE
Redmi Note 8 Pro || force close

### ISSUE THREAD

**Issue by leon-nunes** [KillerInk/FreeDcam#106]
Notes:  
------
- The Log is stored in: "InternalSD/DCIM/FreeDcam/log.txt"
No logs were found under this folder, hence I'm attaching Debug logs from ADB
- Give the Heading a usefull name like, "Huawei P9 does not record 4k"
Done
- Describe your Problem as good as possible.

Phone Model:
Redmi Note 8 Pro, Android 9, MIUI Global 11.0.4
---------------

FreeDcam Version:
4.2
-----------------

Problem Description:
As soon as the App is installed and you open it, the app FC's while running feature detector
[adb_debug_log.txt](https://github.com/KillerInk/FreeDcam/files/4250631/adb_debug_log.txt)

--------------------

**Comment by KillerInk** [comment]
Is fixed with
https://github.com/KillerInk/FreeDcam/commit/543fceb09e70d631630271fdaafe86058a007b41

**Comment by leon-nunes** [comment]
Hey,
Thanks for fixing this, I'm not that well versed with building Android apps or git cherry picking how would I download this build with a specific commit.
The release page is from months ago, should I build the app manually or is there another way thanks.

**Comment by KillerInk** [comment]
when the saf is fully implemented and some other bugs are solved and not a new problem appears, a new release will roll out soon.

**Comment by leon-nunes** [comment]
Hey,

I completely understand, I gave it a shot and built it.

Works like a charm thanks a lot for your help.
