### ISSUE TITLE
Ver. 4.3 crashes on Samsung S5 + Android 9 

### ISSUE THREAD

**Issue by giuliolunati** [KillerInk/FreeDcam#116]
Notes:  
------
- The Log is stored in: "InternalSD/DCIM/FreeDcam/log.txt"
- Give the Heading a usefull name like, "Huawei P9 does not record 4k"
- Describe your Problem as good as possible.

Phone Model: Samsung S5 (klte)
---------------

Android version: 9 (lineage); rooted
-----------------

FreeDcam Version: 4.3
-----------------

Problem Description: Crash on starting. DCIM/FreeDcam don't exist.
--------------------
Here the relevant lines in logcat:

08-13 10:28:06.824   656  2252 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10100000 pkg=troop.com.freedcam cmp=troop.com.freedcam/freed.cam.ActivityFreeDcamMain} from uid 10174
08-13 10:28:06.887   656   752 I ActivityManager: Start proc 15901:troop.com.freedcam/u0a198 for activity troop.com.freedcam/freed.cam.ActivityFreeDcamMain
08-13 10:28:08.468   656  1034 I WindowManager: Screen frozen for +1s529ms due to Window{56ea0c9 u0 Splash Screen troop.com.freedcam}
08-13 10:28:09.117 15901 15988 E AndroidRuntime: Process: troop.com.freedcam, PID: 15901
08-13 10:28:09.117 15901 15988 E AndroidRuntime: 	at freed.file.MediaStoreController.getImagesFromFolder(MediaStoreController.java:290)
08-13 10:28:09.117 15901 15988 E AndroidRuntime: 	at freed.file.MediaStoreController.getFilesFromFolder(MediaStoreController.java:272)
08-13 10:28:09.117 15901 15988 E AndroidRuntime: 	at freed.file.FileListController.LoadFreeDcamDCIMDirsFiles(FileListController.java:133)
08-13 10:28:09.117 15901 15988 E AndroidRuntime: 	at freed.cam.ActivityFreeDcamMain$LoadFreeDcamDcimDirsFilesRunner.process(ActivityFreeDcamMain.java:90)
08-13 10:28:09.117 15901 15988 E AndroidRuntime: 	at freed.image.ImageTask.run(ImageTask.java:21)
08-13 10:28:09.129   656  7463 W ActivityManager:   Force finishing activity troop.com.freedcam/freed.cam.ActivityFreeDcamMain
08-13 10:28:09.141   656   750 I ActivityManager: Showing crash dialog for package troop.com.freedcam u0
08-13 10:28:09.634   656   749 W ActivityManager: Activity pause timeout for ActivityRecord{e2fe72a u0 troop.com.freedcam/freed.cam.ActivityFreeDcamMain t17138 f}
08-13 10:28:09.730 15901 15936 D EventBus: No subscribers registered for event class freed.cam.events.CameraStateEvents$PreviewCloseEvent
08-13 10:28:09.736 15901 15936 D EventBus: No subscribers registered for event class freed.cam.events.CameraStateEvents$PreviewCloseEvent
08-13 10:28:09.770 15901 15936 D EventBus: No subscribers registered for event class freed.cam.events.CameraStateEvents$CameraChangedAspectRatioEvent
08-13 10:28:09.965   437  2187 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{3252ab8 token=Token{750691b ActivityRecord{e2fe72a u0 troop.com.freedcam/freed.cam.ActivityFreeDcamMain t17138}}}#0
08-13 10:28:09.994 15901 15936 D EventBus: No subscribers registered for event class freed.cam.events.CameraStateEvents$PreviewOpenEvent
08-13 10:28:11.965   656  7463 I ActivityManager: Killing 15901:troop.com.freedcam/u0a198 (adj 900): crash
08-13 10:28:12.180   437   585 W SurfaceFlinger: Attempting to destroy on removed layer: aaad853 Application Error: troop.com.freedcam#0
08-13 10:28:12.730   656   787 I system_server: Explicit concurrent copying GC freed 24913(1850KB) AllocSpace objects, 9(324KB) LOS objects, 50% free, 19MB/38MB, paused 170us total 358.303ms

**Comment by KillerInk** [comment]
thx, i think i fixed it the last days

greets
