### ISSUE TITLE
Add an optional sound to indicate photo was taken successfully

### ISSUE THREAD

**Issue by AndySchroder** [KillerInk/FreeDcam#117]
FreeDcam is buggy, but that's all right because it supports lots of features just not possible in other camera programs. However, every time I take a photo, I'm left wondering, did that really take? Please add some kind of sound after the image is saved successfully. It's especially confusing since there is some kind of timer (no idea what it's for) that counts up after you press the "shoot" button. A sound will help know "you're good to go!". For example, maybe some kind of camera clicking sound. Here are some camera clicking noises that could be shortened up to something appropriate: http://bbcsfx.acropolis.org.uk/?cat=photography .

Obviously, everyone isn't going to want this feature, so make it an option to turn off/on as well.

**Comment by KillerInk** [comment]
could get added. 
the timer itself shows how long the capture process take.
when it dissapear the capture is done.
its usefull on long exposures 

greets
