### ISSUE TITLE
Wavelet Denoise = Off garbles up the viewfinder

### ISSUE THREAD

**Issue by AndySchroder** [KillerInk/FreeDcam#119]
Phone Model: Oneplus 6
---------------

FreeDcam Version: 4.3
-----------------

Problem Description:
--------------------

Wavelet Denoise = Off garbles up the viewfinder and has a meaningless image. If I take a picture anyway, it will take a picture, but noise is way higher than DNG files and the image is cropped to a small image.

**Comment by AndySchroder** [comment]
Looks like OpenCamera does a similar thing.

**Comment by KillerInk** [comment]
looks like its a opo problem then and need to get fixed hal side
