### ISSUE TITLE
Xiaomi Redmi note 4 SD Magenta Tint in DNG 

### ISSUE THREAD

**Issue by kamayok3** [KillerInk/FreeDcam#12]
Phone Model:
Redmi Note 4 SD

FreeDcam Version:
Latest Beta 1

Problem Description:
Magenta Tint in DNG eventhough already change the colorpattern to different types. RGGB,BGGR,GRGB,GBRG..... and so on. No success.

**Comment by kamayok3** [comment]
Solved. I need to use GRBG for my Redmi note 4 SD.

**Comment by KillerInk** [comment]
The problem is that the Redmi Note 4 and Redmi Note4x havethe same Build Model and rawsize.
But they have different colorpattern. Its impossible to detect wich is correct.
