### ISSUE TITLE
Separate Camera Specific and Global Settings

### ISSUE THREAD

**Issue by AndySchroder** [KillerInk/FreeDcam#120]
Currently each camera (front, rear primary, rear secondary, etc) each have their own set of values for all settings. Please create camera specific and global settings. For example, I'd like "Grid", "Geo-Tag Location", "Image Level", "External Shutter Trigger", etc. to be global settings, and image resolution, video framerate, etc. to be camera specific settings.

**Comment by KillerInk** [comment]
yes you're right
