### ISSUE TITLE
Crash on launch 

### ISSUE THREAD

**Issue by 33nano** [KillerInk/FreeDcam#128]
Bug log: https://del.dog/emanygraki

Device Info
Oneplus 7 Pro
Android 10

**Comment by KillerInk** [comment]
hi that problem should be fixed already.
waiting now for 7 days that google release the update.
but you can get the latest apk [here](https://github.com/KillerInk/FreeDcam/releases/tag/4.3.8)

**Comment by 33nano** [comment]
Cool, thanks
