### ISSUE TITLE
Freedcam wont work under grapheneOS 2020.10.23.04

### ISSUE THREAD

**Issue by matfechner** [KillerInk/FreeDcam#129]
Notes:  
------
- The Log is stored in: "InternalSD/DCIM/FreeDcam/log.txt"
- Give the Heading a usefull name like, "Huawei P9 does not record 4k"
- Describe your Problem as good as possible.

Phone Model: Pixel 3a on GrapheneOS  https://grapheneos.org/releases#2020.10.23.04
---------------

FreeDcam Version: 4.3.8
-----------------

Problem Description: Freedcam wont work, Display stay black it seems to be that freedcam can not got access to the Camera
--------------------

**Comment by KillerInk** [comment]
Feel free to open issue again when you provide more informations

**Comment by matfechner** [comment]
with the last update this issue was fixed, thx
