### ISSUE TITLE
crash in video recording

### ISSUE THREAD

**Issue by DoctorSubtilis** [KillerInk/FreeDcam#134]
I don't know why but every time I try to record a video, the app crash, or better goes away (from full screen, and becomes a window in background).
I have a Motorola E6 Plus, I tried changing some video settings (max video size: from 0 to 50 mb, f.e.), but nothing to do.

**Comment by KillerInk** [comment]
hi pls try to set max recording time and max file size to 0. then mediarecorder ignores it.
some devices dont like it and crash in that case. 
have to add more feedback to users if something while preparing fails.

**Comment by DoctorSubtilis** [comment]
Thank you. Done, but unsuccessfully.  
I tried to disable audio recording as well, but likewise unsuccessfully...

**Comment by KillerInk** [comment]
Feel free to open issue again when you provide more informations

**Comment by DoctorSubtilis** [comment]
> Feel free to open issue again when you provide more informations
Yes, could you explain how can I provide you the log? Thank you.

**Comment by KillerInk** [comment]
https://github.com/KillerInk/FreeDcam/wiki/How-to-Log

**Comment by DoctorSubtilis** [comment]
Here the log: 
[log.txt](https://github.com/KillerInk/FreeDcam/files/5731261/log.txt)

**Comment by DoctorSubtilis** [comment]
After sending the log, couldn't you religios-open this thread? Thanks!

**Comment by DoctorSubtilis** [comment]
Well, today, after uninstalling and reinstalling the app,  I managed to make a video without crashing.
