### ISSUE TITLE
Evey time i open app it loses jpeg quality setting or video file not saved even after recoding 

### ISSUE THREAD

**Issue by pp058** [KillerInk/FreeDcam#135]
please fix these issue after all it one of the best app

**Comment by pp058** [comment]
my device moto g9 camera 2 api enable Android 10

**Comment by mirh** [comment]
I also had some troubles with media not saving, including also crashes because the right permission wasn't even being asked and I needed to grant it manually (similar to #128 maybe?)
After doing so and setting *twice* "storage location" on external it seemed to work good then.

**Comment by KillerInk** [comment]
Feel free to open issue again when you provide more informations
