### ISSUE TITLE
jepg quality reset

### ISSUE THREAD

**Issue by pp058** [KillerInk/FreeDcam#145]
every time i relaunch the app it lose jepeg quality setting even after showing 50% , 60% set 
it still products huge file size like 100% 
6mb to 12 mb per photo 
please fix this issue 
device moto g9 play Android 10 
camera 2 api enable

**Comment by pp058** [comment]
thanks sir 👍
when was that fixed update release 
i love this app using it from 3 year

**Comment by KillerInk** [comment]
should be fixed with [4.3.51](https://github.com/KillerInk/FreeDcam/releases/tag/4.3.51)
