### ISSUE TITLE
micro sensor not available 

### ISSUE THREAD

**Issue by pp058** [KillerInk/FreeDcam#147]
micro sensor or camera not available in back not showing 
camera 2api 
Android 10 
moto g9

**Comment by KillerInk** [comment]
I don't know what I'd get used for that cam. You have to provide more informations

**Comment by pp058** [comment]
> I don't know what ID get used for that cam. You have to provide more informations

it work fine in 4.3.3 version but not in 4.17 
what kind of information you need tell ??

**Comment by KillerInk** [comment]
it is as it is. on that version some devices didnt find a camera. so it got reverted.
you have to wait till freedcam get multicamera api added. but feel free to contribute, its open source

**Comment by pp058** [comment]
I know its open source but i didn't have the knowledge about Android app building but 
i can be your tester for sure 😄😄
