### ISSUE TITLE
video recording crashed

### ISSUE THREAD

**Issue by fob014** [KillerInk/FreeDcam#151]
many time app crash when start video recording or even changing just different video profile 
Android 10 
camera 2 api enable 
Devices -: not device specific more or less i face this issue on multiple devices eg redmi note 8 pro  , moto g9 , realme 6 pro etc
app version 4.3.17

**Comment by KillerInk** [comment]
think that is fixed with v4.3.38
pls check release section

**Comment by fob014** [comment]
> think that is fixed with v4.3.38
> pls check release section

thanks great work 😀 every major issues fix 
now i die in peace
