### ISSUE TITLE
Flash/Torch not working in Interval mode

### ISSUE THREAD

**Issue by Aulig** [KillerInk/FreeDcam#159]
I've made the following configuration (rest should be default settings):
- Set mode to interval mode
- Set flash mode to single (same issue with torch mode)
- Set shutter fire interval to 10 sec
- Set Duration till interval ends to 1 min

The flash doesn't get activated when it takes a picture in the interval. I don't think the configured interval even makes a difference actually, as I have the same issue independent of the picked settings.

Also, thank you very much for this awesome project - it works better than 99% of the dedicated timelapse apps I could find lol.

**Comment by KillerInk** [comment]
should be fixed with [4.3.51](https://github.com/KillerInk/FreeDcam/releases/tag/4.3.51)
