### ISSUE TITLE
FIX viewfinder image messed up in portrait view #rotation #rotate

### ISSUE THREAD

**Issue by allanlaal** [KillerInk/FreeDcam#164]
**Describe the bug**

![Screenshot_20210802-082351](https://user-images.githubusercontent.com/740826/127808693-9da45536-3d1b-40ea-ac5d-9ccf5b9b2e3f.png)

it only shows a distorted part of the viewfinder. 
landscape works great
reverse landscape also messed up [important for some filming use cases with weird tripod situations]

**To Reproduce**

1. use Android 10
2. disable system autorotation (since it seems FreeDCam handles rotation by itself)
3. disable all rotation apps
4. launch FreeDCam
5. rotate phone physically 4x90° to see the difference

**Expected behavior**

rotation works in all 4 positions like anyone would expect

**Smartphone:**
  Device:

Blackview BV6300Pro

Android w kernel 4.14:

![Screenshot_20210802-083959](https://user-images.githubusercontent.com/740826/127809670-d23cf5f2-67b3-41e8-a3bd-f80f28b7f22a.png)

**Comment by KillerInk** [comment]
not sure how you are able to rotatet it. but that shouldnt work. freedcam is forced to landscape

**Comment by allanlaal** [comment]
my bad, it seems the screen rotation force hack was in effect after stopping the daemon

report invalid, closing
