### ISSUE TITLE
Why isn't this app on the Play Store? 

### ISSUE THREAD

**Issue by feinstein** [KillerInk/FreeDcam#2]
Well the title says it all...why can't I find this as an app on the Play store?

**Comment by KillerInk** [comment]
There are various reasons:
- I'm to lazy to respond to Playstore Commit's and Emails.
- To many bugy/different Camera Api's. Some are impossible to add, without having that device.
- My bad english, or other's english is not existing and he/she write in their homelanguage.
- It's infact to powerfull for most People.
- Ignorant people
- And more stuff...

Coding is a hobby for me. But if it feels like work, the fun is gone.

**Comment by feinstein** [comment]
So, can't you post on the Play Store and ignore all the dumb people out there? Hahaha

You can leave a message on the app's description saying "I don't give support to this App, don't expect me to reply to your emails"

**Comment by KillerInk** [comment]
Its now published again.

**Comment by feinstein** [comment]
I can't find it, could you share the link?

**Comment by KillerInk** [comment]
https://play.google.com/store/apps/details?id=troop.com.freedcam

**Comment by feinstein** [comment]
Thanks!
