### ISSUE TITLE
[Feature Request] video recording: Smooth Skin | Face retouching

### ISSUE THREAD

**Issue by ghost** [KillerInk/FreeDcam#224]
https://private-user-images.githubusercontent.com/42504385/324149658-9324cd07-e0b7-47e6-ba48-c1ce65c4f0a7.mp4

No Smooth Skin, 
People can only use closed source and violations of user privacy Camera App
Like the [B612 camera](https://play.google.com/store/apps/details?id=com.linecorp.b612.android), Beauty Skin. The B612 keeps sending our face data to a China government corporations.

Like Pixel Camera, Video recording Face retouching | Smooth Skin is not support

**Comment by KillerInk** [comment]
hi
thats out of the aim from freedcam. its not meant to be a video or photo editor and apply filter.
that there is a gallery comes from older days, when the stock gallery didnt support the dng format.

i dont know if there is a hidden key for smooth skin on newer camera modules.
but there is some keys for beautyface on xaomi devices. but never tried to get it working
im not up to date.

but feel free to contribute that feature! ^^

greets
