### ISSUE TITLE
Stacking stops. No jpeg files seen.

### ISSUE THREAD

**Issue by SpencerDexter** [KillerInk/FreeDcam#24]
Phone Model:nx549j
---------------

FreeDcam Version:4.1beta7
-----------------

Problem Description:While stacking images if change screen orientation, stacking stops. BTW could you add "select all" button for stacking (I usually stack from 70 to 200 images). One more thing, the app doesn't see ".jpEg" extention.
--------------------

**Comment by KillerInk** [comment]
about .jpEg
freedcam check files depending on file ending. files produced by freedcam have .jpg
maybe a better approach would be to use a contentprovider. but then it need a big rework

select all can get added. or all visibile items.
viewer need more love for sure and has alot potential to get extended.
