### ISSUE TITLE
Can't change the JPEG quality 

### ISSUE THREAD

**Issue by feinstein** [KillerInk/FreeDcam#3]
Phone Model: OnePlus 5
---------------

FreeDcam Version: 4.1alfa27
-----------------

Problem Description: When I try to select some other JPEG quality on the settings menu, the quality is always 85.
--------------------

**Comment by KillerInk** [comment]
you are right. that happens only on cam2

**Comment by KillerInk** [comment]
but it get applied to the cam

**Comment by feinstein** [comment]
I didn't tested that far, so it should be a simple UI fix I guess
