### ISSUE TITLE
Not supported in Play Store

### ISSUE THREAD

**Issue by LosTigeros** [KillerInk/FreeDcam#36]
Phone Model:
MyPhone Infinity IIS (Android 5.1)

FreeDcam Version:
4.1beta5

Problem Description:
I can't update the app from the play store. I'm in beta group and it shows me: 
Your device isn't compatible with this version.

**Comment by KillerInk** [comment]
dont know some people have that problem. infact your device is not blocked. maybe clearing appcache from play help.
