### ISSUE TITLE
How to disable the video file size limit?

### ISSUE THREAD

**Issue by DeadMetaler** [KillerInk/FreeDcam#47]
Phone Model: Xiaomi Redmi Note 4
---------------

FreeDcam Version: 4.1 beta9
-----------------

Problem Description:
--------------------
I'm recording video with camera1 API, 4K, H264/H265, 100Mbps. It does not depend on the codec, but the record is splitting files to 2,7Gb (2.885.875.827 bytes). It's automatically continue to record, but some pause with 1s is present. I'm recording video to internal storage with ext4 filesystem.

This is not acceptable for records of long interviews.

In video profile i change MaxRecordTime to any value but nothing help to record without limit. 

How to disable the file size limit?

**Comment by KillerInk** [comment]
both values are hardcoded inside the Videorecorder
https://github.com/KillerInk/FreeDcam/blob/master/app/src/main/java/freed/cam/apis/basecamera/record/VideoRecorder.java#L112

but i dont remember why. think it had something todo with sdcards and fat32

**Comment by DeadMetaler** [comment]
@KillerInk can you build a version without limit or make a setting for changing this?

**Comment by KillerInk** [comment]
my local repo is a bit messed up. have todo first other things then i will look into it.
