### ISSUE TITLE
No manual control on dng

### ISSUE THREAD

**Issue by Smallchopper48** [KillerInk/FreeDcam#48]
Notes:  
------
my phone can do manual on iso, shutter speed and focus, but cant do that on raw, why?

Phone Model:
Redmi 3s, S5K3L8 Samsung

FreeDcam Version:
4.1beta9

Problem Description:
my phone can do manual on jpeg, but on raw the setting just cant applied

**Comment by KillerInk** [comment]
I think you have to activate the rawdumpinterface to have manuals in api1 on that phone. I think there was also the restriction that you have to set a fix iso like iso100 to use shutterspeed.

**Comment by Smallchopper48** [comment]
just tried that and my phone freeze, is there any other way around?
