### ISSUE TITLE
85% JPG quality after app restart

### ISSUE THREAD

**Issue by Fila127** [KillerInk/FreeDcam#50]
I really like the app and I fully respect all developers. Thumbs up for possibility to turn off denoising and sharpening.
Phone Model:
Xperia X Performance
Android 8.0
FreeDcam Version:
4.1beta9
Problem Description:
If I set JPG quality to 100%, after next startup it will be set only to 85%. I have to change quality to higher value after app restart. I use camera2 api. I found out that 85% is original value of quality in camera2 api. It's not important bug but 85% JPG isn't good for post-processing in the photo editor. 
Thanks in advance.

My English isn't good and I know it. Sorry for it. :)

**Comment by Uriziel01** [comment]
Same on **LG G5** when using latest **4.1beta9**

**Comment by Fila127** [comment]
Thank you a lot! :)

**Comment by Uriziel01** [comment]
@KillerInk enjoy your vacations 😃 Do it whenever it will be comfortable for you, good luck.
