### ISSUE TITLE
Select different audio sources

### ISSUE THREAD

**Issue by droped** [KillerInk/FreeDcam#56]
Currently there is no way to select an audio source and so we are stuck with the default one. However, the default one is too close to my camera and whenever the camera is on, it produces a noise that is very audible in the video. This can be fixed by changing the audio source so I think the feature is useful.

LG G3 d885  
Freedcam 4.1final (from github releases)  
Android 7.1.2

**Comment by KillerInk** [comment]
the mediarecorder is very limited with its audio source input.
i had it set to camcorder some time ago and it crashed on some devices, due that freedcam is now using the default wich works on all devices.

https://developer.android.com/reference/android/media/MediaRecorder.AudioSource

i have first to check if its working as expected bevor i add it

**Comment by KillerInk** [comment]
https://github.com/KillerInk/FreeDcam/pull/69
