### ISSUE TITLE
Redmi 5 Plus - Bayer file

### ISSUE THREAD

**Issue by LosTigeros** [KillerInk/FreeDcam#76]
Phone Model:
Xiaomi Redmi 5 Plus (Vince)

FreeDcam Version:
4.1final

Problem Description:
Created Bayer file can't be used for Raw2Dng.

[Redmi 5 Plus_CameraParameters.txt](https://github.com/KillerInk/FreeDcam/files/2584068/Redmi.5.Plus_CameraParameters.txt)
[2018_11_15_08_17_53.bayer.zip](https://github.com/KillerInk/FreeDcam/files/2584071/2018_11_15_08_17_53.bayer.zip)

There's an DNG profile created by default but it's for Redmi 5, not for Redmi 5 Plus.

**Comment by KillerInk** [comment]
works here without problem.
true size is 4032x3000

**Comment by LosTigeros** [comment]
For me DNG files are empty. 
![screenshot_2018-11-15-16-44-26-953](https://user-images.githubusercontent.com/6253928/48564209-3f83c800-e8f6-11e8-86d1-c9c96d92d4a1.png)
When I try to use Raw2Dng on Bayer file:
![screenshot_2018-11-15-16-46-36-156_troop com freedcam](https://user-images.githubusercontent.com/6253928/48564279-5cb89680-e8f6-11e8-8f8d-57e84a605a33.png)

**Comment by LosTigeros** [comment]
And by the way I'm on MIUI10 Stable after update.

**Comment by LosTigeros** [comment]
Any update?

**Comment by KillerInk** [comment]
![device-2018-11-27-170134](https://user-images.githubusercontent.com/30864229/49094272-29ff8e00-f266-11e8-857b-c33ae62be49c.png)

unknown raw file means freedcam does not know it. and you have to enter the values yourself.

**Comment by lbrunkho** [comment]
I am having the same issue with my Mi A2 Lite, it generates a .bayer file that cannot be read or converted by any application. I have tried the affore mentioned raw2dng and a host of linux applications, darktable, ufraw, and dcraw. freedcam does list the format as bayer-mipi-10rggb but i have no way to open or convert it, any ideas?

i attached a sample raw file and a screen shot of the included gallery app trying to load the image.
[mia2lite.zip](https://github.com/KillerInk/FreeDcam/files/2908604/mia2lite.zip)

**Comment by KillerInk** [comment]
https://github.com/KillerInk/FreeDcam/wiki/How-to-create-a-DngProfile

pls check this. it contains all needed informations
