### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by logos88** [KillerInk/FreeDcam#8]
Would this app be suitable to be put in F-Droid's repos?

https://gitlab.com/fdroid/rfp/issues/158

**Comment by KillerInk** [comment]
Well there a two problems left. The opcode one can get moved in a seperate repo.

The second is a problem. I have no idea how to pass a already reflected instance. The lg lib is not the problem but the typedreference lib. But its needed to create camera2 custom keys.

**Comment by logos88** [comment]
Oks. I hope there will be a solution in the future. It would be nice to have FreeDcam there : )
