### ISSUE TITLE
Dng files not generating previews in Google photo app

### ISSUE THREAD

**Issue by aunqur** [KillerInk/FreeDcam#80]
Phone Model: Mi A1
---------------

FreeDcam Version: 4.2
-----------------

Problem Description:
--------------------
After latest 4.2 update  (dng writer related updates), dng files are no longer generating previews by google photos. 

Ex dng file: https://drive.google.com/file/d/12oc3n8rYDSX5ufRr9ThQeG-TxjytBV6b/view?usp=drivesdk

**Comment by KillerInk** [comment]
Yes, but everywhere else it get shown. And gps ifd works too. Its more a problem from google photos.

**Comment by aunqur** [comment]
Google photos is now OK. I've also checked Photoshop for windows and Lightroom for windows both are working Fine.  But I think there are some more problem in DNG. In windows PC it is not generating thumbnail in file explorer and also not opening in Microsoft Photos app for windows 10. My exported DNG created by Lightroom is displaying in Microsoft Photos app.

Here is a fully working DNG file exported from Lightroom:
