### ISSUE TITLE
Conver DNG to JPG.

### ISSUE THREAD

**Issue by hiepgaf** [KillerInk/FreeDcam#88]
Phone Model:
Google Pixel 2

FreeDcam Version:
4.2

Problem Description:
Hi @KillerInk, Will Freedcam  support convert DNG to JPG with quality similar to JPEGs produced by the vendor hardware, ex: tonemapping, saturation, white balance..?

**Comment by KillerInk** [comment]
hi
maybe someday.
that could get a own project. im currently fixing up bugs, and try some other things.

greets
