### ISSUE TITLE
video upside down

### ISSUE THREAD

**Issue by letkan** [KillerInk/FreeDcam#90]
Phone Model:
Xiaomi MiA2 lite
FreeDcam Version:
4.2
Problem Description:
--------------------
While in picture mode I can turn the phone either right or left for landscape view and the picture orientation is correct, in video mode flipping it to the right takes the video upside down though the view is correct. Turning it to the left it shoots correctly. Is that a bug or what?

Oh, Happy new year!

**Comment by letkan** [comment]
> happy new year. happen that on camera1 or camera2?

camera1
Also, it doesn't want to do 120fps (slow motion), basically I just changed fps in 720p from 30 to 120 and turned off audio capture but the speed is the same.

**Comment by KillerInk** [comment]
hm strange, must check it tomorrow, the problem with the orientation.

about highspeed make sure you set the record mode to highspeed. setting it to 120fps is not enough.
audio caputure should work with 120fps too

**Comment by letkan** [comment]
Aha, thanks, will check it tomorrow.
