### ISSUE TITLE
No HDR and Night mode on Pixel 2 XL

### ISSUE THREAD

**Issue by Kokokokoka** [KillerInk/FreeDcam#94]
Phone Model:
---------------
Pixel 2 XL
FreeDcam Version:
-----------------
4.2
Problem Description:
--------------------
There is no option to use HDR or Night mode on Pixel 2 XL, it's the only thing that prevents me from switching from open camera

**Comment by o0nls0o** [comment]
Do you think dual iso would be possible ? Pp is kind of heavy so it might not work at all.

**Comment by KillerInk** [comment]
@o0nls0o yes should be possible with camera2 and a full device, but dont know the math behind.

**Comment by o0nls0o** [comment]
@KillerInk 

https://www.magiclantern.fm/forum/index.php?topic=7139.0

All about dual iso. : )
