### ISSUE TITLE
Changing video shutter speed has no effect (camera1)

### ISSUE THREAD

**Issue by Tooniis** [KillerInk/FreeDcam#98]
Phone Model:
Xiaomi Mi Note 2, MIUI Global 10.2.1.0(OADMIXM) Stable

FreeDcam Version:
4.2

Problem Description:
With `camera1` API, changing the shutter speed in video mode has absolutely no effect. If changing video shutter speed is not supported by this phone then the option should not be available in the first place.

**Comment by KillerInk** [comment]
Hi
for 90% of the devices out with manual shutter it work. Im to lazy to workaround xiaomis bugy hals.
Also there is no way to check if manual shutter is supported in video mode. That means i have to store more device specific settings.
